### ISSUE TITLE
Limit the number of words in the list of platforms

### ISSUE THREAD

**Issue by evaristoc** [evaristoc/fCC_R3#13]
The current format is nice but some descriptions are too long. A limit to the number of words could be better.

**Comment by Bigghead** [comment]
A custom pipe could work for this, maybe?

https://github.com/Bigghead/Netflix-Clone-2.0/blob/master/client/src/app/Pipes/truncate-string.pipe.ts

Then in your HTML, 
`{{ reallyLongDescription | truncate }}`

**Comment by evaristoc** [comment]
Excellent idea, @Bigghead !!! Didn't cross my mind to be honest. Shame of me.

I can do it, but I will be more than honored to count on your contribution? (*Note*: your work is EXCELLENT!).

Or I will simply hack your solution... In any case, Big Thanks!

**Comment by evaristoc** [comment]
Thanks again, @Bigghead. Done.
